
[normal]
return = "enter"
c = "open_creation_win"
d = "drop_item"
e = "eat_item"
g = "pick_up_item"
h = "open_help_win"
i = "open_item_menu"
o = "open_game_info_win"
q = "drink_item"
r = "release_item"
s = "open_status_win"
w = "open_equip_win"
escape = "open_exit_win"
f12 = "open_debug_command_win"

[dialog]
return = "enter"
escape = "cancel"
tab = "rotate_window_right"
a = "item_infomation"
