[package]
name = "rusted-ruins-map-editor"
version = "0.6.0"
edition = "2018"
authors = ["T. Okubo <t.okubo.rx78+devel@gmail.com>"]

[dependencies]
rusted-ruins-geom = { path = "../geom" }
rusted-ruins-common = { path = "../common", features = ["global_state_obj"] }

gtk = "0.8"
gdk = "0.12"
gio = "0.8"
gdk-pixbuf = "0.8"
cairo-rs = "0.8"
tar = "0.4"

