[package]
name = "rusted-ruins-makepak"
version = "0.5.0"
edition = "2018"
authors = ["T. Okubo <t.okubo.rx78+devel@gmail.com>"]

[dependencies]
anyhow = "1"
lazy_static = "1"
regex = "1"
serde = "1"
serde_derive = "1"
thiserror = "1"
toml = "0.5"
tar = "0.4"
clap = "2"
image = "0.23"
nom = { version = "5", features = ["regexp_macros"] }

[dependencies.rusted-ruins-geom]
path = "../geom"

[dependencies.rusted-ruins-common]
path = "../common"


